package com.fossil.assetmanagementsystem.enums;

public enum StatusEnum {
    ASSET_ASSIGNED, ASSET_RETURNED, ASSET_REPAIRED, ASSET_REPLACED,
    ASSET_DISPOSED,ASSET_DISPOSAL_PENDING,ASSET_REVALUED,ASSET_WRITTEN_OFF

}
